// Welcome kit endpoint. The hub's bottom-right popup POSTs { code } here; the code was
// generated by /api/slack-newhire when the hiring manager ran /new-hire in Slack.
// Codes are stateless: the survey answers travel inside the code, signed with
// WELCOME_SECRET, so there is no database. Content comes from welcome.json + clients.json.

const crypto = require('crypto');

function welcomeSecret() {
  return process.env.WELCOME_SECRET || process.env.SLACK_SIGNING_SECRET || 'carrara-onboarding-hub';
}

const COUNTRY_LABELS = { US: 'United States', AR: 'Argentina', AU: 'Australia', OTHER: 'your country' };

function decode(code) {
  const parts = String(code || '').trim().split('.');
  if (parts.length !== 2) return null;
  const [b64, sig] = parts;
  const mine = crypto.createHmac('sha256', welcomeSecret()).update(b64).digest('hex').slice(0, 10);
  try {
    if (!crypto.timingSafeEqual(Buffer.from(mine), Buffer.from(sig))) return null;
  } catch (e) { return null; }
  let packed;
  try { packed = Buffer.from(b64, 'base64url').toString('utf8'); } catch (e) { return null; }
  const f = packed.split('|').map(decodeURIComponent);
  if (f.length < 5) return null;
  return { name: f[0], country: f[1], project: f[2], client: f[3], manager: f[4], managerId: f[5] || '' };
}

module.exports = async (req, res) => {
  if (req.method !== 'POST') return res.status(405).json({ error: 'POST only' });
  res.setHeader('Cache-Control', 'no-store');

  const who = decode((req.body || {}).code);
  if (!who) return res.status(401).json({ error: 'That code does not look right. Check for missing characters and try again.' });

  const config = JSON.parse(JSON.stringify(require('../welcome.json')));
  const clients = require('../clients.json').clients || [];
  const codex = require('../codex.json').clients || {};

  // Eric's POps tool sends the offering as free-ish text ("People Ops", "talent",
  // "Marketing/Growth"), so normalize through the alias map before looking it up.
  // Unknown offerings fall through to `other` rather than 404ing the whole kit.
  const offerings = config.offerings || {};
  const offeringKey = (raw) => {
    const k = String(raw || '').trim();
    if (offerings[k]) return k;
    const alias = (config.offeringAliases || {})[k.toLowerCase()];
    return alias && offerings[alias] ? alias : 'other';
  };
  const team = offerings[offeringKey(who.project)] || offerings.other;
  const country = config.countries[who.country] || config.countries.OTHER;
  const clientInfo = clients.find((c) => c.name === who.client) || null;
  const clientCodex = (clientInfo && codex[clientInfo.name]) || {};

  // week-one syncs: hiring manager first, then the client lead, then the team's defaults.
  // Names come from different sources ("Sol S." in clients.json vs "Sol Silbenberg" from
  // Slack), so match on first name + last initial rather than the exact string.
  const samePerson = (a, b) => {
    if (!a || !b) return false;
    const pa = a.trim().toLowerCase().split(/\s+/);
    const pb = b.trim().toLowerCase().split(/\s+/);
    if (pa[0] !== pb[0]) return false;
    const la = (pa[1] || '').replace(/\./g, '');
    const lb = (pb[1] || '').replace(/\./g, '');
    return !la || !lb || la.charAt(0) === lb.charAt(0);
  };
  // manager map is keyed by full name; match loosely so "Heath" or "Kenna Anderson"
  // still resolve to the right entry rather than silently dropping the section.
  const managerEntry = (() => {
    const map = config.managers || {};
    if (map[who.manager]) return map[who.manager];
    const hit = Object.keys(map).find((n) => samePerson(n, who.manager));
    return hit ? map[hit] : null;
  })();

  // the manager has their own section in the popup, so they anchor the dedup but are not re-listed
  const sync = [];
  const seen = who.manager ? [who.manager] : [];
  if (clientInfo && clientInfo.lead && !seen.some((n) => samePerson(n, clientInfo.lead))) {
    sync.push({ name: clientInfo.lead, why: 'leads the ' + clientInfo.name + ' account' });
    seen.push(clientInfo.lead);
  }
  // people the hiring manager actually works with, then the offering's defaults
  ((managerEntry && managerEntry.meet) || []).forEach((s) => {
    if (!seen.some((n) => samePerson(n, s.name))) { sync.push(s); seen.push(s.name); }
  });
  (team.syncWith || []).forEach((s) => {
    // the generic placeholder is only useful when we could not resolve the actual lead
    if (/^your client/i.test(s.name) && clientInfo && clientInfo.lead) return;
    if (!seen.some((n) => samePerson(n, s.name))) { sync.push(s); seen.push(s.name); }
  });

  const links = [];
  if (clientInfo && clientInfo.domain) {
    links.push({ label: clientInfo.name + ' website', href: 'https://' + clientInfo.domain, external: true });
  }
  links.push({ label: 'All clients and who leads them', href: '#/clients' });
  (config.commonLinks || []).forEach((l) => links.push(l));

  return res.status(200).json({
    name: who.name,
    firstName: who.name.split(/\s+/)[0] || who.name,
    manager: { name: who.manager, id: who.managerId || '' },
    countryLabel: country.label || COUNTRY_LABELS[who.country] || who.country,
    client: clientInfo ? {
      name: clientInfo.name,
      domain: clientInfo.domain || '',
      lead: clientInfo.lead || '',
      work: clientInfo.work || [],
      // business lines from the codex, so the kit shows the same tags as the clients page
      tags: (clientCodex.projectTypes && clientCodex.projectTypes.length)
        ? clientCodex.projectTypes : (clientInfo.work || []),
      // the narrative lives in codex.json, which is what the client page already renders
      about: clientCodex.about || clientInfo.description || '',
      engagement: clientCodex.engagement || []
    } : null,
    team: { key: offeringKey(who.project), label: team.label, how: team.how || [], examples: team.examples || [] },
    country: { key: who.country, label: country.label, notes: country.notes || [] },
    managerBrief: managerEntry ? { runs: managerEntry.runs || '', accounts: managerEntry.accounts || [] } : null,
    syncWith: sync,
    links
  });
};
