// Welcome kit endpoint. The hub's bottom-right popup POSTs { code } here; the code was
// generated by /api/slack-newhire when the hiring manager ran /new-hire in Slack.
// Codes are stateless: the survey answers travel inside the code, signed with
// WELCOME_SECRET, so there is no database. Content comes from welcome.json + clients.json.

const crypto = require('crypto');

function welcomeSecret() {
  return process.env.WELCOME_SECRET || process.env.SLACK_SIGNING_SECRET || 'carrara-onboarding-hub';
}

const COUNTRY_LABELS = { US: 'United States', AR: 'Argentina', AU: 'Australia', OTHER: 'your country' };

const { parseSyncWith } = require('../my-onboarding.js');

// POps' plan-read endpoint. The default is the live POps host so Eric has ONE
// secret to paste at the ceremony, not two; the override exists for staging.
// Read at call time, not at module load, exactly like welcomeSecret() and like
// POPS_PLAN_TOKEN below: a value captured at require() time is a value the
// verifier cannot override and a stale value in any runtime that mutates env
// after the first import.
function planUrl() {
  return process.env.POPS_PLAN_URL || 'https://carrara-pops.work/api/hub-plan';
}

/**
 * This hire's manager plan from POps, or null.
 *
 * NEVER THROWS, and every non-answer is the same answer: no plan key, no
 * secret, a 404, a 500, a timeout, a body that is not an object -- all null,
 * and the kit renders without the plan block. POps being down must degrade a
 * new hire's page, never break it.
 *
 * The bearer is POPS_PLAN_TOKEN, a secret of its own -- not POPS_HUB_TOKEN --
 * so the two directions rotate independently. Without it this function does not
 * make a request at all, which is what keeps a deploy that lands before the
 * secret a no-op.
 */
async function fetchPlan(planKey) {
  const token = process.env.POPS_PLAN_TOKEN;
  if (!planKey || !token) return null;
  try {
    const r = await fetch(planUrl().replace(/\/+$/, '') + '/' + encodeURIComponent(planKey), {
      headers: { Authorization: 'Bearer ' + token }
    });
    if (!r.ok) return null;
    const j = await r.json();
    return j && typeof j === 'object' && !Array.isArray(j) ? j : null;
  } catch (e) {
    return null;
  }
}

/** A plan field, or null. Anything that is not a non-empty string is nothing --
 *  the section renders one block per non-null field. */
function planText(plan, key) {
  const v = plan && plan[key];
  return typeof v === 'string' && v.trim() ? v : null;
}

function decode(code) {
  const parts = String(code || '').trim().split('.');
  if (parts.length !== 2) return null;
  const [b64, sig] = parts;
  const mine = crypto.createHmac('sha256', welcomeSecret()).update(b64).digest('hex').slice(0, 10);
  try {
    if (!crypto.timingSafeEqual(Buffer.from(mine), Buffer.from(sig))) return null;
  } catch (e) { return null; }
  let packed;
  try { packed = Buffer.from(b64, 'base64url').toString('utf8'); } catch (e) { return null; }
  const f = packed.split('|').map(decodeURIComponent);
  if (f.length < 5) return null;
  // f[6] is v7's plan key. Absent on every code minted before 2026-08-17, which
  // is why it defaults to '' rather than making the code invalid: an old code
  // still unlocks a kit, just without the plan block.
  return { name: f[0], country: f[1], project: f[2], client: f[3], manager: f[4], managerId: f[5] || '', planKey: f[6] || '' };
}

module.exports = async (req, res) => {
  if (req.method !== 'POST') return res.status(405).json({ error: 'POST only' });
  res.setHeader('Cache-Control', 'no-store');

  const who = decode((req.body || {}).code);
  if (!who) return res.status(401).json({ error: 'That code does not look right. Check for missing characters and try again.' });

  const config = JSON.parse(JSON.stringify(require('../welcome.json')));
  const clients = require('../clients.json').clients || [];

  const team = config.teams[who.project] || config.teams.other;
  const country = config.countries[who.country] || config.countries.OTHER;
  const clientInfo = clients.find((c) => c.name === who.client) || null;

  // week-one syncs: hiring manager first, then the client lead, then the team's defaults.
  // Names come from different sources ("Sol S." in clients.json vs "Sol Silbenberg" from
  // Slack), so match on first name + last initial rather than the exact string.
  const samePerson = (a, b) => {
    if (!a || !b) return false;
    const pa = a.trim().toLowerCase().split(/\s+/);
    const pb = b.trim().toLowerCase().split(/\s+/);
    if (pa[0] !== pb[0]) return false;
    const la = (pa[1] || '').replace(/\./g, '');
    const lb = (pb[1] || '').replace(/\./g, '');
    return !la || !lb || la.charAt(0) === lb.charAt(0);
  };
  // the manager has their own section in the popup, so they anchor the dedup but are not re-listed
  const sync = [];
  const seen = who.manager ? [who.manager] : [];
  if (clientInfo && clientInfo.lead && !seen.some((n) => samePerson(n, clientInfo.lead))) {
    sync.push({ name: clientInfo.lead, why: 'leads the ' + clientInfo.name + ' account' });
    seen.push(clientInfo.lead);
  }
  (team.syncWith || []).forEach((s) => {
    // the generic placeholder is only useful when we could not resolve the actual lead
    if (/^your client/i.test(s.name) && clientInfo && clientInfo.lead) return;
    if (!seen.some((n) => samePerson(n, s.name))) { sync.push(s); seen.push(s.name); }
  });

  // The plan, and the one place the manager's answer outranks the derivation
  // (spec decision 4): the Brain's client-lead + team-defaults list stays as
  // the FALLBACK, so a blank answer and every pre-v7 code still render syncs.
  const plan = await fetchPlan(who.planKey);
  const stated = parseSyncWith(planText(plan, 'sync_with') || '');
  const syncWith = stated.length ? stated : sync;

  const links = [];
  if (clientInfo && clientInfo.domain) {
    links.push({ label: clientInfo.name + ' website', href: 'https://' + clientInfo.domain, external: true });
  }
  links.push({ label: 'All clients and who leads them', href: '#/clients' });
  (config.commonLinks || []).forEach((l) => links.push(l));

  return res.status(200).json({
    name: who.name,
    firstName: who.name.split(/\s+/)[0] || who.name,
    manager: { name: who.manager, id: who.managerId || '' },
    countryLabel: country.label || COUNTRY_LABELS[who.country] || who.country,
    client: clientInfo ? {
      name: clientInfo.name,
      domain: clientInfo.domain || '',
      lead: clientInfo.lead || '',
      work: clientInfo.work || []
    } : null,
    team: { key: who.project, label: team.label, how: team.how || [] },
    // Country-SPECIFIC content is gone (spec decision 5): day-one comms already
    // carry the pay and invoicing instructions for each employment type, and
    // two sources of truth on somebody's pay is one too many. The key and label
    // stay -- the code still packs a country, and mint.js still warns on an
    // unknown one.
    country: { key: who.country, label: country.label },
    // The one generic line that replaces the country notes. One string in
    // welcome.json, editable without touching code.
    payNote: config.payNote || '',
    syncWith: syncWith,
    // Echoed so the round-trip verifier can see the seventh field decode, and so
    // an empty plan block can be diagnosed from the response alone ('' means the
    // code predates v7; a key with a null plan means POps did not answer). Not a
    // secret to the recipient: it arrived inside the code they just entered, and
    // it opens nothing on its own -- POps' /api/hub-plan also demands the
    // POPS_PLAN_TOKEN bearer, which never leaves this server.
    planKey: who.planKey,
    // The manager's own words, straight through: the same keys POps returns,
    // which are the manager_hub question keys. sync_with is NOT echoed here --
    // it has already become syncWith above, and two copies would drift.
    plan: plan ? {
      manager_intro: planText(plan, 'manager_intro'),
      thirty_days: planText(plan, 'thirty_days'),
      sixty_days: planText(plan, 'sixty_days'),
      ninety_days: planText(plan, 'ninety_days')
    } : null,
    links
  });
};
